openapi: 3.0.0
info:
  title: OpenAPI спецификация Тестового задания
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1/
    description: Dev server  
  
paths:
  /get-dogs:
    get:
      tags:
        - dogs 
      summary: Получение списка собак
      description: Метод возвращает список собак
      operationId: getDogs
      parameters:
        - name: owner_id
          in: query
          description: ID владельца. Eсли передать, то вернется список собак для конкретного владельца, если нет - список всех собак  
          required: false
          schema:
            type: integer
            default: 12345
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Dogs'
        '400':
          description: Некорректные входные данные. Возвращает список атрибутов с ошибками
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Error'         

components:
  schemas:
    Dog:
      type: object
      required:
        - pet_id
        - name
        - breed
      properties:
        pet_id:
          type: integer
          example: 10
        name:
          type: string
          example: Граф
        breed:
          type: string
          example: Сибирский хаски
        age:
          type: integer
          example: 7
        owner_id:
          type: integer
          example: 100  
    Dogs:
      type: object
      properties:
        dogs:
          type: array
          items:
            $ref: '#/components/schemas/Dog'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: Некорректные входные данные